enforce_dependencies: true
enforce_privacy: false
dependencies:
  - packs/shared
  - packs/accounts
  - packs/users
  - packs/statuses
  - packs/relationships
  - packs/interactions
  - packs/notifications
  - packs/conversations
  - packs/media
  - packs/polls
  - packs/tags
  - packs/timelines
  - packs/trends
  - packs/domain_blocking
  - packs/moderation
  - '.'
public_path: app/public/
owner: Platform
