# Announcements domain
enforce_dependencies: false
enforce_privacy: false

dependencies:
  - packs/shared
  - packs/accounts

metadata:
  owner: Communications Team
  description: Server announcements and reactions
