enforce_dependencies: true
enforce_privacy: false
dependencies:
  - packs/shared
  - packs/accounts
  - packs/statuses
  - packs/notifications
  - packs/relationships
  - packs/trends
  - packs/federation
  - '.'
public_path: app/public/
