enforce_dependencies: true
enforce_privacy: false
dependencies:
  - packs/shared
  - packs/accounts
  - packs/statuses
  - packs/media
  - packs/notifications
  - packs/federation
  - '.'
public_path: app/public/
owner: Content
