enforce_dependencies: true
enforce_privacy: false
dependencies:
  - packs/shared
  - packs/accounts
  - packs/users
  - packs/statuses
  - packs/relationships
  - packs/notifications
  - packs/media
  - packs/timelines
  - packs/trends
  - packs/federation
  - packs/admin
  - '.'
public_path: app/public/
owner: Moderation
